import { test, expect } from "@playwright/test";
import { mkdtempSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { parseApng } from "./fixtures/apng";

/**
 * Tracer-bullet e2e for the animated-WebP line (issue #28).
 *
 * This is the v3 end-to-end proof that the animated-WebP pipeline is wired:
 * upload a real, browser-decodable animated WebP → `detectAnimation` flags it
 * animated with the right frame count (extending #16's GIF-only detection to
 * WebP) → the worker routes to `processAnimated` (no WebP/APNG branch inside
 * the orchestrator — it only calls the generalised codec seam, #24) →
 * `browserAnimatedWebpDecoder` decodes every frame via WebCodecs `ImageDecoder`
 * (#26) → faithful Lanczos upscales each frame → `browserAnimatedApngEncoder`
 * re-encodes via UPNG.js true-colour (#27) → download an APNG whose structure
 * proves the round-trip survived. PRD stories #8–#12.
 *
 * **Output format is device-determined (ADR-0007).** Chromium has WebCodecs, so
 * the resolved codec pair's `webCodecs===true` branch fires and the encoder is
 * UPNG.js — the animated output is **APNG (true-colour)**, not GIF. GIF output
 * only happens on devices *without* WebCodecs (the degrade path); that branch
 * is exercised under Vitest via `animatedCodecPair.test.ts` and a dedicated
 * degrade-path unit test added in this slice. The degrade path is *not* driven
 * from Playwright because `addInitScript` runs on the main thread only and the
 * codec pair is resolved inside the worker (`browserPipelineDeps`), where the
 * `ImageDecoder` global is not mockable from the test.
 *
 * The fixture (`e2e/fixtures/animated.webp`) is a real, browser-decodable
 * animated WebP, generated by `scripts/make-animated-webp.mjs`: a hand-built
 * 16×16 3-frame gradient GIF89a transcoded to animated WebP via sharp/libvips
 * (the only dependency-free route to a libwebp-canonical file real decoders
 * accept — see the script header). 16×16 frames keep it tiny; durations
 * 100/150/200ms let timing assertions discriminate frames. Each frame is a
 * diagonal gradient over a 256-colour palette, so the faithful Lanczos 4K
 * upscale interpolates thousands of intermediate colours — forcing UPNG.js's
 * lossless path to true-colour (colour type 6), which the assertion below
 * checks. A 4K faithful upscale of a 16×16 (square) source lands at 3840×3840.
 *
 * The single-frame (static) WebP line is *not* this spec's concern — it is
 * covered by `webp.spec.ts`, which asserts a static WebP routes to the still
 * path and never touches `processAnimated`. This spec only exercises the
 * multi-frame path.
 */
const FIXTURE_DIR = dirname(fileURLToPath(import.meta.url));
const ANIMATED_WEBP = join(FIXTURE_DIR, "fixtures", "animated.webp");

test("animated WebP: detected frame count + 'animation preserved' notice", async ({ page }) => {
  await page.goto("/");

  // Upload the real animated WebP via the hidden single-image file input.
  const fileInput = page.locator('input[type="file"]').first();
  await fileInput.setInputFiles(ANIMATED_WEBP);

  // The animated notice renders for a WebP source too (detection extended to
  // WebP, #16→#26). The copy says "Animated WebP" and reports the frame count.
  await expect(page.getByTestId("animated-notice")).toBeVisible();
  await expect(page.getByTestId("animated-frame-count")).toContainText(/3 frames?/);
  await expect(page.getByTestId("animated-notice")).toContainText(/Animated WebP/);
  await expect(page.getByTestId("animated-notice")).toContainText(
    /animation is preserved/i,
  );

  // The detection-only "treated as a still" notices must NOT show — this WebP
  // is genuinely animated and routes to processAnimated, not the still path.
  await expect(page.getByTestId("animated-webp-notice")).toHaveCount(0);
  await expect(page.getByTestId("apng-notice")).toHaveCount(0);

  // Issue #29: for an animated input the output format is device-determined and
  // the selector is read-only. Chromium has WebCodecs (ImageDecoder), so the
  // device is on the high-fidelity branch — the label must say APNG (true
  // colour), not GIF. The still-path PNG/WebP/JPEG cards are not rendered.
  await expect(page.getByTestId("animated-output-label")).toContainText(/APNG/i);
  await expect(page.getByTestId("animated-output-label")).toContainText(/true colour/i);
  await expect(page.getByTestId("output-format-png")).toHaveCount(0);
  await expect(page.getByTestId("output-format-webp")).toHaveCount(0);
  await expect(page.getByTestId("output-format-jpeg")).toHaveCount(0);
});

test("animated WebP: faithful per-frame upscale → playable 4K APNG (frames + dims + timing preserved, true-colour)", async ({ page }) => {
  const dir = mkdtempSync(join(tmpdir(), "imageto24-webp-e2e-"));
  const outPath = join(dir, "upscaled.apng");

  await page.goto("/");

  const fileInput = page.locator('input[type="file"]').first();
  await fileInput.setInputFiles(ANIMATED_WEBP);

  // Confirm the animated routing is in effect before running.
  await expect(page.getByTestId("animated-frame-count")).toContainText(/3 frames?/);

  // Faithful is the default mode; select 4K.
  await page.getByTestId("tier-4K").click();

  // Trigger the upscale. processAnimated → WebCodecs decode (#26) → faithful
  // Lanczos per frame → UPNG.js APNG encode (#27). The fixture is 16×16
  // (square), so a 4K faithful upscale (long edge 3840) lands at 3840×3840.
  await page.getByTestId("upscale-button").click();

  // Per-frame progress should advance to 3/3 (PRD story #10). It may fire and
  // settle quickly, so wait for the terminal result-dimensions signal rather
  // than asserting an intermediate frame-progress value.
  await expect(page.getByTestId("result-dimensions")).toContainText("3840 × 3840", {
    timeout: 240_000,
  });

  // The download button's label carries the device-determined extension (#29):
  // APNG on this Chromium device, so it reads "… APNG" — no mismatch between
  // the label and the bytes the run emits (ADR-0007 honest output naming).
  await expect(page.getByTestId("download")).toContainText(/APNG/);

  // Download the result and capture it. On this Chromium device the output is
  // an APNG (PNG-signatured), per ADR-0007 — the label above and the bytes
  // below agree (issue #29 AC: "format shown matches what the pipeline emits").
  const downloadPromise = page.waitForEvent("download");
  await page.getByTestId("download").click();
  const download = await downloadPromise;
  // The suggested filename also carries the .apng extension (no .gif mismatch).
  expect(download.suggestedFilename()).toMatch(/\.apng$/i);
  await download.saveAs(outPath);

  // PNG signature ⇒ the bytes are an APNG, not a GIF.
  const downloaded = readFileSync(outPath);
  expect(downloaded[0]).toBe(0x89);
  expect(downloaded[1]).toBe(0x50); // 'P'
  expect(downloaded[2]).toBe(0x4e); // 'N'
  expect(downloaded[3]).toBe(0x47); // 'G'

  // Re-parse the downloaded APNG's chunk structure and assert the round-trip:
  //   - it is genuinely animated (carries an `acTL` chunk) — playable
  //   - frame count preserved (3 → 3, PRD story #8/9)
  //   - dimensions upscaled to the 4K canvas (3840×3840)
  //   - colour type 6 ⇒ true-colour RGBA (no 256-colour quantization — the
  //     colour-fidelity point of #27; GIF would cap this)
  //   - per-frame timing preserved (100/150/200ms carried through, story #11)
  //   - every chunk's CRC is valid (well-formed file)
  const apng = parseApng(downloaded);
  expect(apng.animated).toBe(true);
  expect(apng.frameCount).toBe(3);
  expect(apng.width).toBe(3840);
  expect(apng.height).toBe(3840);
  expect(apng.colourType).toBe(6); // true-colour RGBA — the fidelity win
  expect(apng.crcsValid).toBe(true);
  expect(apng.delays).toEqual([100, 150, 200]);
});
